### ISSUE TITLE
Proyecto: Preparación del Dataset y Análisis Exploratorio de Datos: EDA

### ISSUE THREAD

**Issue by furrutiav** [furrutiav/lab-mds-2022#12]
Luego, se les solicita que realizen un EDA en donde hagan tareas generales como:

- Analizar los tipos de datos y distribuciones de las variables a través de histogramas.
- Generar visualizaciones de las interacciones (como por ejemplo, una scatter matrix) en las distintas variables.
- Ver las correlaciones entre las distintas variables y los valores faltantes de cada una de estas. 
- Proyectar los datos con UMAP para ver si existen relaciones entre las distintas variables de forma bi o tri dimensional.
- Reportar los patrones y relaciones interesantes.

Como también tareas particulares como:

- Genenrar un scatterplot de `budget` vs `target` (ex-revenue).
- Buscar las peliculas de Marvel y hacer un scatter plot que en el eje x contenga `budget` y en el eje y `target` (ex-revenue). Utilice las columnas `` como `` y como `hover_name` .
- Graficar a través de un gráfico de barras las 50 productoras más frecuentes. Incluya la cantidad de `nans`.
- Graficar a través de un gráfico de barras los 50 artistas más frecuentes. 

Las tareas mencionadas anteriormente son lo mínimo. Sin embargo, ojalá no se restringan a lo mencionado anteriormente y exploren aún más en profundidad. Pueden usar tanto **`pandas`** como **plotly** y ``pandas profiling`` para esto. En el caso de generar un profile, adjuntar los resultados en el notebook.

**Comment by abeldano** [comment]
Casi listo: 
tareas generales: falta comentar patrones interesantes
tareas específicas : intentar hacer las últimas 2 de forma más prolija (ocupé 2 "for"), además problemas de identificación de strings (guiones de split de artistas se confunden con guiones en los mismos strings)

***si hay tiempo, intentar hacer mas tareas.

Dividí el proyecto en 4 notebooks segun recomendacion del enunciado.

**Comment by abeldano** [comment]
EDA listo

Falta concluir despues de generar modelos de clasificacion y regresion.
Falta introducción
