### ISSUE TITLE
Proyecto: Regresión: Creación del modelo Dummy y del Baseline

### ISSUE THREAD

**Issue by furrutiav** [furrutiav/lab-mds-2022#17]
*En esta sección crearán el modelo más básico posible que resuelva el segundo problema, el de las ganancias. La idea de este modelo usarlo como comparación para que en el siguiente paso lo puedan mejorar.*

- Generar un modelo Dummy que les permita comparar más adelante si su baseline de regresión es mejor que el azar.
- Generar un pipeline para la regresión con un regresor relativamente sencillo de utilizar (a su elección, recomendado: arbol de decisión).
- Evaluar ambos modelos según las métricas de evaluación y reportar.

**Comment by abeldano** [comment]
Listo
